# Use the crowd_nav generative model
pomdp_model: crowd_nav
# POMDP discount factor
discount_factor: 0.95
# Max number of steps before the problem terminates
n_steps: 200
# Number of parallel simulations during planning
num_envs: 30000
# Plan until timeout
max_sampled_episodes: 0
# Visualize the environment after every step
simulate_headless: False
# VOPP's temperature parameter
eta: 0.5
# Maximum depth of the search trees
max_search_depth: 90
# Number of particles used to approximate beliefs
num_belief_particles: 30000

# Map & pedestrian parameters
map_size_x: 50
map_size_y: 40
num_peds: 300
num_near_peds: 6
curiosity_distance: 4.0
curiosity_prob: 0.5
move_prob: 0.9
