logfile_postfix: ma_rocksample_large

discount_factor: 0.983
n_steps: 600
num_envs: 60000
max_sampled_episodes: 0 # Plan until timeout
simulate_headless: False
pomdp_model: ma_rocksample
eta: 2.0
alpha_t: 0.5
max_search_depth: 90
num_belief_particles: 500000

map_size: 50
num_rocks: 50
