logfile_postfix: unc_navigation

discount_factor: 0.983
n_steps: 60
num_envs: 50000
max_sampled_episodes: 0 # Plan until timeout
simulate_headless: False
pomdp_model: unc_navigation
eta: 2.0
max_search_depth: 60
num_belief_particles: 300000
